Fix pre-commit hook for Cppcheck exhaustive checks
sysprog21/lab0-c pull request #154
Opened 2024-02-21 15:45 UTC by 25077667

Refine the pre-commit hook to enforce a minimum Cppcheck VERSIon of 1.90, alerting users with an error message and guidance on compiling Cppcheck from source if their version is outdated.

Additionally, upgrade the hook to include the
"--check-level=exhaustive" option for Cppcheck versions 2.11 and ABOVe, ENSURing a comprehensive analysis.
This adjustment caters to the enhanced capabilities available from version 2.11, promoting more detailed code quality checks.

Eliminate the "--check-level=" is needed after 2.11.
#153

2024-02-21 15:48 UTC, jserv commented on scripts/pre-commit.hook
> +# Append --check-level=exhaustive if the version is 2.11+
You should explain the reason why option `--check-level=exhaustive` is appended.

2024-02-21 16:02 UTC, jserv commented on scripts/pre-commit.hook
> +# "log2_lshift16.h:15.1 ValueFlow analysis is limited in log2_lshift16. Use --check-level=exhaustive if full analysis is wanted."
It is not necessary to validate log2_lshift16.h because this file was primarily intended to illustrate the concept behind logarithm calculation. In other words, its omission was intentional. I don't expect someone would modify this file.

2024-02-21 16:23 UTC, jserv commented on scripts/pre-commit.hook
> +# "log2_lshift16.h:15.1 ValueFlow analysis is limited in log2_lshift16. Use --check-level=exhaustive if full analysis is wanted."
Alternatively, skip the checking of file `log2_lshift16.h`.

2024-02-21 16:50 UTC, 25077667 commented on scripts/pre-commit.hook
> +# "log2_lshift16.h:15.1 ValueFlow analysis is limited in log2_lshift16. Use --check-level=exhaustive if full analysis is wanted."
@jserv It seems hard to manually select log2_lshift16.h for out current script. It might takes a large changes commit. So, I suppress checkLevelNormal for `log2_lshift16.h`.

2024-02-22 07:24 UTC, jserv requested changes
Improve git commit message to reflect what you proposed to change.

2024-02-23 14:56 UTC, 25077667 commented
@jserv What's about this title?

2024-02-23 15:31 UTC, jserv requested changes
Make git commit message informative.

2024-02-24 17:53 UTC, 25077667 commented
@jserv Is this okay? "Suppress Cppcheck constant check"

2024-02-25 02:41 UTC, jserv commented
> @jserv Is this okay? "Suppress Cppcheck constant check"

The subject is acceptable, but there is no commit message body.

2024-02-27 13:54 UTC, merged