Integrate linenoise with web server
sysprog21/lab0-c pull request #162
Opened 2024-02-29 11:29 UTC by vax-r

## Summary

In the previous version of console implementation, we tried to integrate tiny-web-server to enable the ability of processing commands from web requests. As the result, the package linenoise which is responsible for
command-line auto-complete needs to be disabled during the running time of tiny-web-server. Because the `line_edit()` function in linenoise.c doesn't have the ability to handle web requests correctly.

When we start the web server, we use `cmd_select` in console.c and use `select` system call to monitor web socket file descriptor and stdin_fd at the same time, however, this ability should present in the `line_edit` function in linenoise.c so we can process commands from command-line and from web requests at the same time.

That's the reason I re-design the linenoise implementation and make some modification to put `select()` system call in `line_edit` so we can have the full ability to use web server and linenoise package in command-line at the same time.

2024-02-29 13:38 UTC, jserv requested changes
Use `git rebase` instead of `git merge`.

2024-02-29 13:42 UTC, jserv commented on linenoise.h
> +void linenoise_webfd(int fd);
Don't change the public header of linenoise. We would stick to the APIs defined by linenoise upstream.

2024-03-01 01:22 UTC, vax-r commented on linenoise.h
> +void linenoise_webfd(int fd);
Ok, then is it ok to modify the header file of web ? I need a way to access the web file descriptor in linenoise.

2024-03-01 02:26 UTC, jserv requested changes
Refine the subject of git commit messages: make it compliant with https://cbea.ms/git-commit/

2024-03-01 02:28 UTC, jserv commented on linenoise.c
> +    fd_set set;
Minimize the changes against `linenoise.c`, which is considered as the work of upstream. Instead, specify hooks for the same purpose.

2024-03-01 12:37 UTC, jserv commented on linenoise.c
> +
Don't change this line. Minimize the necessary changes.

2024-03-01 12:37 UTC, jserv commented on linenoise.c
> +#include <sys/select.h>
Don't change the inclusion.

2024-03-01 12:38 UTC, jserv commented on linenoise.c
> +
Ditto. Minimize the changes.

2024-03-01 12:39 UTC, jserv commented
Remove "Successfully" from the subject of git commit messages. Make it informative.

2024-03-01 13:27 UTC, jserv commented on linenoise.c
> +    int result = web_select(l.buf, l.ifd);
The proposed change lacks refinement, as it tightly integrates web server operations with the linenoise package. Linenoise is intended to be a streamlined and functional package, offering basic command line editing capabilities universally. Therefore, it's advisable to incorporate the function hook within the main loop of linenoise. This strategy will enable a standard method for callback registration, allowing web server interactions to be executed alongside linenoise's main loop, thus achieving a more decoupled approach.

2024-03-01 14:03 UTC, vax-r commented on linenoise.c
> +    int result = web_select(l.buf, l.ifd);
My understanding is that the main loop of linenoise is the same as the function `linenoise()` in linenoise.c , can I say that ?

2024-03-01 14:13 UTC, jserv commented on linenoise.c
> +    int result = web_select(l.buf, l.ifd);
> My understanding is that the main loop of linenoise is the same as the function `linenoise()` in linenoise.c , can I say that ?

No, the main loop of linenoise package appears in `line_edit` function, and you check the callbacks such as `completion_callback` for the execution of user-defined functions. Always program in an elegant way.

2024-03-01 16:19 UTC, jserv commented on linenoise.c
> +/* Register the web select function to monitor web socket file descriptor and
Don't mention web related messages. Make it generic when possible.

2024-03-01 16:51 UTC, jserv commented on linenoise.c
> +        if (select_callback != NULL) {
Would it be sufficiently clear to name it `select_callback`? It might confuse someone already familiar with linenoise's internals, particularly its "selected mode." In this case, you should consider refining the name of the newly-added callback to prevent ambiguity.

2024-03-01 16:55 UTC, jserv commented on linenoise.c
> +/* Register the select function to monitor multiple file descriptor from
In the context of line editing, the operation "select" is a feature, and the changes you've made pertain to multiplexing. In other words, you may choose a different term besides "select" for clearer explanation.

2024-03-01 16:59 UTC, jserv requested changes
Avoid using [backtick](https://en.wikipedia.org/wiki/Backtick) in git commit message for the sake of maximum editor compatibility. You can use (double) quotation marks instead.

2024-03-01 17:40 UTC, jserv commented on linenoise.c
> +        if (select_callback != NULL) {
Further refinement is required.

2024-03-02 04:46 UTC, vax-r commented on linenoise.c
> +        if (select_callback != NULL) {
Sorry I didn't noticed this part yesterday, I've made some adjustment.
I choose the word "multiplexing" and looked for its definition in [dictionary](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E/multiplexing) , I think the term fits our situation here.

2024-03-02 05:02 UTC, jserv commented on linenoise.c
> +void line_set_multiplexing_callback(line_multiplexing_callback_t *fn)
Replace "multiplexing" with "eventmux," which stands for the multiplexor of incoming events.

2024-03-02 05:02 UTC, jserv commented on web.h
> +int web_select(char *buf);
Refine the naming.

2024-03-02 06:01 UTC, jserv commented on linenoise.c
> +/* Register a function to perform I/O multiplexing to monitor multiple file
Improve the descriptions by explaining the functionality of this callback invoked inside the main loop of linenoise. You should discuss the use case for example.

2024-03-02 06:04 UTC, jserv requested changes
Refine the subject "Integrate linenoise package with web server," which is a bit misleading. In fact, web server has been integrated into the whole project, and the proposed change is not exactly referred as the integration effort. Instead, it was meant to inject the main loop of line editing by introducing an extra callback which can interoperate with the web server.

2024-03-02 06:06 UTC, jserv commented on web.c
> +int server_fd;
If this variable is not intended to be public, declare it as a static storage.

2024-03-02 06:27 UTC, jserv commented
This patch looks good to me. I defer to @eecheng87 for confirmation.

2024-03-02 06:40 UTC, vax-r commented
> This patch looks good to me. I defer to @eecheng87 for confirmation.

Can I mention this PR in my homework-1 note ? or I should refine my commit in my personal repository and mentioned it instead ?

2024-03-02 06:46 UTC, jserv commented
> Can I mention this PR in my homework-1 note ? or I should refine my commit in my personal repository and mentioned it instead ?

Go ahead. Don't go off-topic here.

2024-03-04 03:26 UTC, merged

2024-03-04 03:26 UTC, jserv commented
Thank @vax-r for contributing!