Add explainations for q_ascend and q_descend
sysprog21/lab0-c pull request #170
Opened 2024-03-10 14:28 UTC by backink

Add supllementary explainations for q_ascend and q_descend, indicating required memory operations that must be implemented in these functions.

2024-03-10 15:11 UTC, jserv commented on queue.h
> + * The memory allocated to nodes that are removed must be freed after their
Rephrase as following:
> Memory allocated to removed nodes must be freed.

The latter is slightly more direct.

2024-03-11 16:05 UTC, jserv requested changes
Execute `sha1sum queue.h` and update the content of file `scripts/checksums`.

2024-03-14 00:21 UTC, backink commented
Ok Thanks for the comment.
I'll look into how to implement this.

2024-03-18 11:51 UTC, jserv commented
Close via commit 7a02fb25796fcfffbea7e8406af0ff14e9b4ce02

2024-03-18 11:51 UTC, closed without merging

2024-03-18 11:52 UTC, jserv commented
Thank @backink for contributing!