Refactor test_calloc and introduce alloc
sysprog21/lab0-c pull request #172
Opened 2024-03-16 04:24 UTC by komark06

This commit introduces a generic alloc function to handle both test_malloc and test_calloc operations based on the provided alloc_func_t. Additionally, it implements the test_calloc function to allocate memory and initialize it to zero.

2024-03-16 15:18 UTC, jserv requested changes
Revise the subject of git commit message and pull request.

Quote from Wikipedia:
"code refactoring is the process of restructuring existing computer code — changing the factoring — without changing its external behavior."

It is evident that the external behavior is changed since the introduction of callc harness hook.

2024-03-17 04:38 UTC, komark06 commented
Thank you for your review. I've updated the subject for both the git commit message and the pull request.

2024-03-17 05:04 UTC, jserv commented on harness.c
> +    TEST_CALLOC = 0,
Swap the order of the identifiers.

2024-03-17 05:05 UTC, jserv commented on harness.c
> +} alloc_func_t;
`alloc_func_t` is misleading since the above were meant to be identifiers which can not represent the functions.

2024-03-17 05:05 UTC, jserv commented on harness.c
> +    if (func_name == TEST_MALLOC) {
Use array to aggregate the messages.

2024-03-17 08:37 UTC, komark06 commented on harness.c
> +
- Remove the value associated with the enum to avoid the need to change its order.
- Rename `alloc_func_t` to `alloc_t` for clarity.

2024-03-17 08:37 UTC, komark06 commented on harness.c
> +
Utilize an array of pointers to reference various error messages

2024-03-17 08:40 UTC, jserv commented on harness.c
> +                            "Calls to calloc disallowed"};
Append a comma (`,`) right after "Calls to calloc disallowed" to make clang-format happy.

2024-03-17 08:40 UTC, jserv commented on harness.c
> +
Ditto. Make clang-format happy.

2024-03-17 09:07 UTC, jserv commented on harness.c
> +        "Calls to malloc disallowed",
Improve the messages, making them grammatical correct.

2024-03-17 09:08 UTC, jserv commented on harness.c
> +        "Calls to malloc disallowed",
Rename to  `msg_alloc_forbidden`.

2024-03-17 09:08 UTC, jserv commented on harness.c
> +    char *fail_alloc_msg[] = {
Ditto. Rename to `msg_alloc_failure`.

2024-03-17 09:16 UTC, komark06 commented
Improve error messaging and precisely rename variables.

2024-03-17 11:57 UTC, merged

2024-03-17 11:58 UTC, jserv commented
Thank @komark06 for contributing. Be aware of the amended subject.

2024-03-17 12:20 UTC, komark06 commented
Thank you for your feedback.