Cmdextend
sysprog21/lab0-c pull request #44
Opened 2020-09-16 00:29 UTC by eecheng87

Rebase commit into `e2bec85` and `03e549b`

2020-09-16 00:52 UTC, jserv requested changes
Minimize the functional changes. Redo the commits.

2020-09-16 01:01 UTC, jserv commented
Did you rebase?

2020-09-16 01:01 UTC, eecheng87 commented
> Did you rebase?

squash two commit into one

2020-09-16 01:03 UTC, jserv commented
> squash two commit into one

Then, why are there conflicting files?

2020-09-16 01:06 UTC, eecheng87 commented
> > squash two commit into one
> 
> Then, why are there conflicting files?

Let me resolve them

2020-09-16 01:13 UTC, jserv commented
> Let me resolve them

Use `git rebase` rather than `git mere`. Alternatively, you can create a new branch and re-add files, that sounds stupid but straightforward.

2020-09-16 03:49 UTC, jserv commented on console.c
> +        linenoiseHistorySave("history.txt"); /* Save the history on disk. */
Rename the history file to `.cmd_history`, so that users will be not aware of its existence.

2020-09-16 03:50 UTC, jserv commented on README.md
> +Integrate [linenoise](https://github.com/antirez/linenoise) to `qtest`. Contain following user-friendly features:
Update external project listing.

2020-09-16 03:53 UTC, jserv commented on console.c
> +static bool has_infile = false;
Is it possible to eliminate this variable?

2020-09-16 03:54 UTC, jserv commented on scripts/pre-commit.hook
> +CPPCHECK_suppresses="--inline-suppr harness.c --suppress=unmatchedSuppression:harness.c --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=variableScope"
Don't change the suppression configurations. Instead, just skip linenoise.[ch].

2020-09-16 04:02 UTC, jserv commented on Makefile
> +		linenoise.o
Indent.

2020-09-16 04:02 UTC, jserv requested changes
Improve the subject of this pull request.

2020-09-16 04:37 UTC, jserv commented on console.c
> +                    "history.txt"); /* Save the history on disk. */
Avoid hardcoded string. Instead, use macro to specify history file.

2020-09-17 11:09 UTC, eecheng87 commented on console.c
> +                    "history.txt"); /* Save the history on disk. */
Fixed

2020-09-17 11:10 UTC, eecheng87 commented on Makefile
> +		linenoise.o
Fixed

2020-09-17 11:10 UTC, eecheng87 commented on scripts/pre-commit.hook
> +CPPCHECK_suppresses="--inline-suppr harness.c --suppress=unmatchedSuppression:harness.c --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=variableScope"
Fixed

2020-09-17 11:10 UTC, eecheng87 commented on console.c
> +        linenoiseHistorySave("history.txt"); /* Save the history on disk. */
Fixed

2020-09-17 18:58 UTC, jserv commented on console.c
> +        linenoiseHistorySave("history.txt"); /* Save the history on disk. */
Did you fix this line?

2020-09-17 22:35 UTC, eecheng87 commented on console.c
> +        linenoiseHistorySave("history.txt"); /* Save the history on disk. */
Sorry for careless, fixed!

2020-09-18 02:39 UTC, merged

2020-09-18 02:39 UTC, jserv commented
Thank @eecheng87 for contributing!