Replace `atoi()` with `strtol()`
sysprog21/lab0-c pull request #55
Opened 2021-02-27 13:46 UTC by nickchenchj

The behavior is undefined if the argument passed to `atoi()` is
not convertible to `int`. This issue could be solved by using
`strtol()`.

2021-02-27 15:03 UTC, jserv requested changes
Change the subject of git commit message to "Replace atoi with strtol"
That is, no backticks (`) should be used in git commit messages.

2021-02-27 15:05 UTC, jserv commented on qtest.c
> +            level = strtol(optarg, &endptr, 10);
Reduce the scope of `endptr`. That is, rewrite as following:
```c
case 'v': {
    char *endptr;
    level = strtol(optarg, &endptr, 10);
    ...
}
```

2021-02-27 17:05 UTC, jserv requested changes
The subject of this pull request was not addressing what you changed. You fixed error-prone option parsing in fact. Revise the commit message(s) accordingly.

2021-02-27 17:07 UTC, jserv commented on qtest.c
> +                fprintf(stderr, "FATAL: Invalid verbosity level.\n");
Remove "FATAL: " from the error message for consistency.

2021-02-27 17:59 UTC, nickchenchj commented on qtest.c
> +                fprintf(stderr, "FATAL: Invalid verbosity level.\n");
Is "Improve consistency of error message" suitable for this commit?

2021-02-28 01:57 UTC, jserv commented
Use `git rebase -i` to rework the commits. Let's keep single git commit and write down better commit message.

2021-02-28 11:49 UTC, merged

2021-02-28 11:49 UTC, jserv commented
Thank @nickchenchj for contributing!