Fix pre-commit hook static analysis error
sysprog21/lab0-c pull request #67
Opened 2022-02-17 18:25 UTC by jasperlin1996

Suppress the nullPointer error from Cppcheck when invoking "list_entry"
from list.h. There is a \_\_typeof\_\_(((type *) 0)->member) in the
container_of macro, which is legal based on ANSI C standard but
triggers the error.

2022-02-17 18:35 UTC, jserv commented
Can you verify with various versions of Cppcheck? That is, from Cppech v1.9 to recent v2.7.

2022-02-17 23:35 UTC, jasperlin1996 commented
@jserv I've verified that this issue exists from Cppcheck v2.0 to Cppcheck v.2.7.
This is the code snippet I used for the test:
```c
#include "lab0-c/queue.h"

int main() {
    struct list_head *head = {&head, &head};
    element_t node = {"Testing\n", head};
    list_entry(head, element_t, list);
    return 0;
}
```
And this is the experiment log:
```
** Cppcheck v1.90 passes the test **
** Cppcheck v2.0 failed to compile **
** Cppcheck v2.1 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.2 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.3 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.4 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.4.1 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.5 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.6 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.6-rc1 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.6.1 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.6.2 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.6.3 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
** Cppcheck v2.7 failed to pass the test**
Checking /~/test.c ... Checking /~/test.c: LIST_POISONING... Checking /~/test.c: __GNUC__... /~/test.c:6:2: error: Null pointer dereference: (struct element_t*)0 [nullPointer] list_entry(head, element_t, list); ^
```

2022-02-18 01:03 UTC, jserv requested changes
Append `unmatchedSuppression` at the of `CPPCHECK_suppresses`. That is,
```diff
@@ -3,7 +3,9 @@
 CPPCHECK_suppresses="--inline-suppr harness.c --suppress=unmatchedSuppression:harness.c --suppress=missingIncludeSystem \
 --suppress=unusedFunction:linenoise.c --suppress=variableScope:linenoise.c \
 --suppress=nullPointerRedundantCheck:report.c \
---suppress=nullPointer:qtest.c"
+--suppress=nullPointer:qtest.c \
+--suppress=nullPointer:queue.c \
+--suppress=unmatchedSuppression:queue.c"
 CPPCHECK_OPTS="-I. --enable=all --error-exitcode=1 --force $CPPCHECK_suppresses ."
 
 RETURN=0
```

Otherwise, Cppcheck will complain as following:
```
queue.c:-1:0: information: Unmatched suppression: nullPointer [unmatchedSuppression]
```

2022-02-18 08:02 UTC, jasperlin1996 commented
@eecheng87 Squash finished.

2022-02-18 08:04 UTC, merged