Rewrite comment with kernel-doc style
sysprog21/lab0-c pull request #85
Opened 2022-03-05 05:40 UTC by eecheng87

Close #84

2022-03-05 15:51 UTC, jserv requested changes
Remove the wording "Attempt to" in file "queue.c"

2022-03-05 17:21 UTC, jserv commented on queue.h
> + *
Add a longer description.

2022-03-05 17:22 UTC, jserv commented on queue.h
> + * q_new() - attempt to create empty queue
Remove the use of "attempt to", which is not necessary.

2022-03-06 12:46 UTC, jserv commented on queue.h
> + * q_remove_head() - attempt to remove element from tail of queue
No "attempt".

2022-03-06 12:46 UTC, jserv commented on queue.h
> + * q_release_element() - attempt to release element
Ditto.

2022-03-06 12:47 UTC, jserv commented on queue.h
> + * q_release_element() - attempt to release element
You should emphasize on the internal use.

2022-03-06 12:48 UTC, jserv commented on queue.h
>   * Referenceerence:
Fix typo. Should be "Reference"

2022-03-06 12:50 UTC, jserv requested changes
Annotate the members in `element_t` as well.

2022-03-06 12:51 UTC, jserv commented on queue.h
> + * q_free() - attempt to free all storage used by queue, no effect if header is
Ditto. No "attempt"

2022-03-06 12:53 UTC, jserv commented on queue.h
> +void static inline q_release_element(element_t *e)
The prototype should be
```c
static inline void q_release_element(element_t *e)
```

2022-03-06 12:55 UTC, jserv commented on queue.h
> + * No effect if q is NULL or empty. In addition, if q has only one element, do
`q` is ambiguous. The parameter is one instance of `struct list_head`.

2022-03-06 13:15 UTC, eecheng87 commented on queue.h
> + * q_release_element() - attempt to release element
Should I remove all "attempt" in queue.h?

2022-03-06 13:17 UTC, jserv commented on queue.h
> + * q_release_element() - attempt to release element
Exactly. No "attempt to" in queue.[ch].

2022-03-06 13:19 UTC, jserv commented on queue.h
> + * q_insert_tail() - attempt to insert element at tail of queue
Correct the grammar. Should be "insert an element at the tail"

2022-03-06 13:21 UTC, jserv commented on queue.h
> + * q_size() - attempt to get the size of the queue
Capitalize the summary. That is, "Get the size" instead of "get the size."

2022-03-07 01:51 UTC, jserv commented on queue.h
> + * This function is only for internal use, it should not be modified.
Change the description to the following:
> This function is intended for internal use only.

2022-03-07 01:53 UTC, jserv commented on queue.h
> + * q_remove_head() - Remove element from head of queue
Should be "the element"

2022-03-07 01:53 UTC, jserv commented on queue.h
> + * q_remove_tail() - Remove element from tail of queue
Ditto.

2022-03-07 01:54 UTC, jserv commented on queue.h
> + * q_delete_mid() - Delete the middle node in list
Don't confuse the developers who read this document. Always say "queue" if you are referring the functions starting with `q_`.

2022-03-07 09:25 UTC, merged