Fix the do_sort error message
sysprog21/lab0-c pull request #88
Opened 2022-04-02 18:40 UTC by bochengC

In the do_sort function, using the strcasecmp function to check the final list fit the requirement or not. But strcasecmp function cares about the order of a letter. So, if a list after sorted is "F d e f" error message will show. But actually it is correct order sorted by ascii code.
Replace the strcasecmp by strcmp. Strcmp(str* s1, str* s2) function compare the letter by ascii code and return >0 integer when s1's ascii code larger then s2's ascii code.

2022-04-03 04:44 UTC, eecheng87 commented
Hi @bochengC , please squash those two commits into one (by `git rebase -i`).

2022-04-03 08:07 UTC, bochengC commented
Done, please check again.

2022-04-03 08:28 UTC, jserv requested changes
Don't mention the function name `do_sort` in the subject of git commit message. Instead, you should summarize what you intended to do.

2022-04-03 08:51 UTC, bochengC commented
I try to use new subject.

2022-04-29 07:16 UTC, jserv commented
@bochengC, would you rework this pull request?

2022-04-29 08:03 UTC, bochengC commented
@jserv, Yes, I did it. The 6a7750c commit is the newest version that modify the subject and squash two commits into one.

2022-04-29 12:31 UTC, jserv commented
> @jserv, Yes, I did it. The [6a7750c](https://github.com/sysprog21/lab0-c/commit/6a7750c889345a7759f492d6701e46ea2c1a2e8f) commit is the newest version that modify the subject and squash two commits into one.

At present, the subject "Fix the incorrectly showing error message" did not relieve the concerns I mentioned earlier -- it is neither informative nor meaningful to developers who wish to learn from git log. In the proposed change, string comparison function was substituted, and you should summarize in git commit message. Again, improve the subject for both pull request and git commit message.

2022-04-29 13:41 UTC, jserv commented
> @jserv , I modify the subtitle and the git messages. Thanks for your teaching.

Changing from `strcasecmp` to `strcmp` is not a matter of correctness but behavior consistency. The proposed subject was not accurate.

2022-04-29 13:59 UTC, bochengC commented
@jserv , I replace "incorrect" with "inconsistent".

2022-04-29 14:02 UTC, jserv commented
> @jserv , I replace "incorrect" with "inconsistent".

I defer to @eecheng87 for reviewing.

2022-04-29 14:11 UTC, merged